### ISSUE TITLE
demo app 

### ISSUE THREAD

**Issue by Sangeetharhythm** [bootcards/demoapp#69]
I downloaded the demoapp application ...but not working properly ..
 plz  mail me the running demo application in my email id (angelagolda@gmail.com)

**Comment by markleusink** [comment]
Just tested it and "It works on my machine" :-)

Here's a quick install guide (just tested on my Mac):

* You should have **git**, **node (npm)** and **bower** installed on your local machine.
* Clone the sample project: `git clone https://github.com/bootcards/demoapp.git`
* Go in to the newly created folder (demoapp).
* Load all dependencies: run a `npm install` and a `bower install`
* Once that is done, you can start up the demo app using `node app.js`. It should then be accessible at `http://localhost:3000`.

**Comment by Sangeetharhythm** [comment]
m having windows 7 and visual studio2008 in my system .. m not able to run
this application in my system ...


Actually m creating an application which must be portable on (mobile ,
tablets and laptop) .I want to implement the same in my asp.net project ....

Plz help me its urgent for me .



 ---
*Thanks & Regards*

*Sangeetha D*

 *Go green. **Please consider the environment before printing this email.**
Do not print this email unless it is absolutely necessary. Let’s preserve
our environment.*

**Comment by markleusink** [comment]
You need NodeJS to run the demo app. I can't help you with re-building it in Visual Studio: no experience with that.

**Comment by Sangeetharhythm** [comment]
k thanks mark



 ---
*Thanks & Regards*

*Sangeetha D*

 *Go green. **Please consider the environment before printing this email.**
Do not print this email unless it is absolutely necessary. Let’s preserve
our environment.*
