### ISSUE TITLE
Form pjax does not work

### ISSUE THREAD

**Issue by JorgeGoias** [bootcards/demoapp#70]
Form Button Save does not work.
in bootcards-demo-app.js, line 128:
    $(document)
    .pjax('a[data-pjax]')
    .on('submit', 'form[data-pjax]', function(event) {
        //use pjax to submit forms
        $.pjax.submit(event);
    })
When click in Save button, he acts like Cancel button.
None submit event is fired to server, why?

Thanks.

**Comment by markleusink** [comment]
See the README file. The save function isn't meant to be working. The demo app was created to show how to apply the classes for the UI components, not as a demo on how to write an application.

**Comment by JorgeGoias** [comment]
I not looking how write applications.

I only questioning why submit event is not fired.

Best,

Jorge Goiás

---

De: Mark Leusink notifications@github.com
Enviado: terça-feira, 21 de junho de 2016 03:56:53
Para: bootcards/demoapp
Cc: JorgeGoias; Author
Assunto: Re: [bootcards/demoapp] Form pjax does not work (#70)

See the README file. The save function isn't meant to be working. The demo app was created to show how to apply the classes for the UI components, not as a demo on how to write an application.

##

**Comment by markleusink** [comment]
I've used the code described here https://github.com/defunkt/jquery-pjax but for some reason it doesn't work anymore. Had a look but couldn't figure out why.

BTW: if I would now have to write a similar app, I would use some JavaScript framework like Angular, Vue, or other. Makes it a lot easier and maintainable.
